-- MySQL Script generated by MySQL Workbench
-- Tue 09 Sep 2025 01:42:07 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema croissantdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema croissantdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `croissantdb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema school_sys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school_sys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school_sys` ;
USE `croissantdb` ;

-- -----------------------------------------------------
-- Table `croissantdb`.`student_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`student_ticket` (
  `ticketnr` INT NOT NULL AUTO_INCREMENT,
  `verloopdatum` DATE NOT NULL,
  `aanmaaksdatum` DATE NOT NULL,
  PRIMARY KEY (`ticketnr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `croissantdb`.`docent_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`docent_ticket` (
  `d_ticketnr` INT NOT NULL AUTO_INCREMENT,
  `verloopdatum` DATE NOT NULL,
  `aanmaaksdatum` DATE NOT NULL,
  PRIMARY KEY (`d_ticketnr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `croissantdb`.`docent_has_student_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`docent_has_student_ticket` (
  `docent_docentnr` INT NOT NULL,
  `docent_docent_ticket_d_ticketnr` INT NOT NULL,
  `student_ticket_ticketnr` INT NOT NULL,
  PRIMARY KEY (`docent_docentnr`, `docent_docent_ticket_d_ticketnr`, `student_ticket_ticketnr`),
  INDEX `fk_docent_has_student_ticket_student_ticket1_idx` (`student_ticket_ticketnr` ASC) VISIBLE,
  CONSTRAINT `fk_docent_has_student_ticket_student_ticket1`
    FOREIGN KEY (`student_ticket_ticketnr`)
    REFERENCES `croissantdb`.`student_ticket` (`ticketnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `croissantdb`.`klas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`klas` (
  `klasnr` INT NOT NULL AUTO_INCREMENT,
  `klastype` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`klasnr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `croissantdb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`account` (
  `accountnr` INT NOT NULL AUTO_INCREMENT,
  `aanmaakstijd` TIME NOT NULL,
  `voornaam` VARCHAR(80) NOT NULL,
  `achternaam` VARCHAR(80) NOT NULL,
  `wachtwoord` VARCHAR(80) NOT NULL,
  `telefoonnr` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `geslacht` VARCHAR(10) NOT NULL,
  `isDocent` TINYINT NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`accountnr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `croissantdb`.`account_has_student_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`account_has_student_ticket` (
  `account_accountnr` INT NOT NULL,
  `student_ticket_ticketnr` INT NOT NULL,
  PRIMARY KEY (`account_accountnr`, `student_ticket_ticketnr`),
  INDEX `fk_account_has_student_ticket_student_ticket1_idx` (`student_ticket_ticketnr` ASC) VISIBLE,
  INDEX `fk_account_has_student_ticket_account1_idx` (`account_accountnr` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_student_ticket_account1`
    FOREIGN KEY (`account_accountnr`)
    REFERENCES `croissantdb`.`account` (`accountnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_has_student_ticket_student_ticket1`
    FOREIGN KEY (`student_ticket_ticketnr`)
    REFERENCES `croissantdb`.`student_ticket` (`ticketnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `croissantdb`.`account_has_docent_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`account_has_docent_ticket` (
  `account_accountnr` INT NOT NULL,
  `docent_ticket_d_ticketnr` INT NOT NULL,
  PRIMARY KEY (`account_accountnr`, `docent_ticket_d_ticketnr`),
  INDEX `fk_account_has_docent_ticket_docent_ticket1_idx` (`docent_ticket_d_ticketnr` ASC) VISIBLE,
  INDEX `fk_account_has_docent_ticket_account1_idx` (`account_accountnr` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_docent_ticket_account1`
    FOREIGN KEY (`account_accountnr`)
    REFERENCES `croissantdb`.`account` (`accountnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_has_docent_ticket_docent_ticket1`
    FOREIGN KEY (`docent_ticket_d_ticketnr`)
    REFERENCES `croissantdb`.`docent_ticket` (`d_ticketnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `croissantdb`.`account_has_klas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`account_has_klas` (
  `account_accountnr` INT NOT NULL,
  `klas_klasnr` INT NOT NULL,
  PRIMARY KEY (`account_accountnr`, `klas_klasnr`),
  INDEX `fk_account_has_klas_klas1_idx` (`klas_klasnr` ASC) VISIBLE,
  INDEX `fk_account_has_klas_account1_idx` (`account_accountnr` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_klas_account1`
    FOREIGN KEY (`account_accountnr`)
    REFERENCES `croissantdb`.`account` (`accountnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_has_klas_klas1`
    FOREIGN KEY (`klas_klasnr`)
    REFERENCES `croissantdb`.`klas` (`klasnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `croissantdb`.`account_has_docent_has_student_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `croissantdb`.`account_has_docent_has_student_ticket` (
  `account_accountnr` INT NOT NULL,
  `docent_has_student_ticket_docent_docentnr` INT NOT NULL,
  `docent_has_student_ticket_docent_docent_ticket_d_ticketnr` INT NOT NULL,
  `docent_has_student_ticket_student_ticket_ticketnr` INT NOT NULL,
  PRIMARY KEY (`account_accountnr`, `docent_has_student_ticket_docent_docentnr`, `docent_has_student_ticket_docent_docent_ticket_d_ticketnr`, `docent_has_student_ticket_student_ticket_ticketnr`),
  INDEX `fk_account_has_docent_has_student_ticket_docent_has_student_idx` (`docent_has_student_ticket_docent_docentnr` ASC, `docent_has_student_ticket_docent_docent_ticket_d_ticketnr` ASC, `docent_has_student_ticket_student_ticket_ticketnr` ASC) VISIBLE,
  INDEX `fk_account_has_docent_has_student_ticket_account1_idx` (`account_accountnr` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_docent_has_student_ticket_account1`
    FOREIGN KEY (`account_accountnr`)
    REFERENCES `croissantdb`.`account` (`accountnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_has_docent_has_student_ticket_docent_has_student_t1`
    FOREIGN KEY (`docent_has_student_ticket_docent_docentnr` , `docent_has_student_ticket_docent_docent_ticket_d_ticketnr` , `docent_has_student_ticket_student_ticket_ticketnr`)
    REFERENCES `croissantdb`.`docent_has_student_ticket` (`docent_docentnr` , `docent_docent_ticket_d_ticketnr` , `student_ticket_ticketnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `school_sys` ;

-- -----------------------------------------------------
-- Table `school_sys`.`student_has_docent_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_sys`.`student_has_docent_ticket` (
  `student_studentnr` VARCHAR(30) NOT NULL,
  `student_student_ticket_ticketnr` INT NOT NULL,
  `docent_ticket_d_ticketnr` INT NOT NULL,
  PRIMARY KEY (`student_studentnr`, `student_student_ticket_ticketnr`, `docent_ticket_d_ticketnr`),
  INDEX `fk_student_has_docent_ticket_docent_ticket1_idx` (`docent_ticket_d_ticketnr` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_docent_ticket_docent_ticket1`
    FOREIGN KEY (`docent_ticket_d_ticketnr`)
    REFERENCES `croissantdb`.`docent_ticket` (`d_ticketnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;